import { Router } from "express";

import userRoutes from "./userRoutes";
import authRoutes from "./authRoutes";
import settingRoutes from "./settingRoutes";
import contactRoutes from "./contactRoutes";
import ticketRoutes from "./ticketRoutes";
import whatsappRoutes from "./whatsappRoutes";
import instagramAccountRoutes from "./instagramAccountRoutes";
import messageRoutes from "./messageRoutes";
import whatsappSessionRoutes from "./whatsappSessionRoutes";
import queueRoutes from "./queueRoutes";
import companyRoutes from "./companyRoutes";
import planRoutes from "./planRoutes";
import ticketNoteRoutes from "./ticketNoteRoutes";
import quickMessageRoutes from "./quickMessageRoutes";
import helpRoutes from "./helpRoutes";
import dashboardRoutes from "./dashboardRoutes";
import queueOptionRoutes from "./queueOptionRoutes";
import scheduleRoutes from "./scheduleRoutes";
import tagRoutes from "./tagRoutes";
import contactLabelRoutes from "./contactLabelRoutes";
import contactListRoutes from "./contactListRoutes";
import contactListItemRoutes from "./contactListItemRoutes";
import campaignRoutes from "./campaignRoutes";
import campaignSettingRoutes from "./campaignSettingRoutes";
import announcementRoutes from "./announcementRoutes";
import chatRoutes from "./chatRoutes";
import invoiceRoutes from "./invoicesRoutes";
import subscriptionRoutes from "./subScriptionRoutes";
import ticketTagRoutes from "./ticketTagRoutes";
import filesRoutes from "./filesRoutes";
import promptRoutes from "./promptRouter";
import queueIntegrationRoutes from "./queueIntegrationRoutes";
import forgotsRoutes from "./forgotPasswordRoutes";
import flowDefaultRoutes from "./flowDefaultRoutes";
import flowBuilder from "./flowBuilderRoutes";
import flowCampaignRoutes from "./flowCampaignRoutes";
import userRatingRoutes from "./userRatingRoutes";
import ratingTemplateRoutes from "./ratingTemplateRoutes";
import groupRoutes from "./groupRoutes";
import appointmentRoutes from "./appointmentRoutes";
import crmRoutes from "./crmRoutes";
import inventoryRoutes from "./inventoryRoutes";
import aiAgentRoutes from "./aiAgentRoutes";
import aiProviderCredentialRoutes from "./aiProviderCredentialRoutes";
import automationOrchestratorRoutes from "./automationOrchestratorRoutes";
import automationToolsRoutes from "./automationToolsRoutes";
import automationEvidenceRoutes from "./automationEvidenceRoutes";
import automationLiveRolloutRoutes from "./automationLiveRolloutRoutes";
import automationCognitivePlanningRoutes from "./automationCognitivePlanningRoutes";
import automationExecutionOrchestratorRoutes from "./automationExecutionOrchestratorRoutes";
import automationActionExecutionRoutes from "./automationActionExecutionRoutes";
import automationRuntimeIntegrationRoutes from "./automationRuntimeIntegrationRoutes";
import automationExecutionFeedbackRoutes from "./automationExecutionFeedbackRoutes";
import automationCognitiveMemoryRoutes from "./automationCognitiveMemoryRoutes";
import automationMcpRoutes from "./automationMcpRoutes";
import automationLearningRoutes from "./automationLearningRoutes";
import automationMultiAgentRoutes from "./automationMultiAgentRoutes";
import automationObservabilityRoutes from "./automationObservabilityRoutes";
import automationScalabilityRoutes from "./automationScalabilityRoutes";
import automationProductionRoutes from "./automationProductionRoutes";
import knowledgeBaseRoutes from "./knowledgeBaseRoutes";


import notificationRoutes from "./notificationRoutes";
import systemSettingRoutes from "./systemSettingRoutes";
import platformSuperRoutes from "./platformSuperRoutes";
import backupRoutes from "./backupRoutes";
import stickerRoutes from "./stickerRoutes";
import systemAdminRoutes from "./systemAdminRoutes";
const routes = Router();

routes.use(systemSettingRoutes);
routes.use(systemAdminRoutes);
routes.use(platformSuperRoutes);
/** Alias para proxies/Nginx que montam a API em `/api` (ex.: POST /api/platform/super-admins). */
routes.use("/api", platformSuperRoutes);
routes.use(backupRoutes);

routes.use(userRoutes);
routes.use(notificationRoutes);
routes.use("/auth", authRoutes);
routes.use(settingRoutes);
routes.use(contactRoutes);
routes.use(ticketRoutes);
routes.use(whatsappRoutes);
routes.use(instagramAccountRoutes);
routes.use(messageRoutes);
routes.use(stickerRoutes);
routes.use(whatsappSessionRoutes);
routes.use(queueRoutes);
routes.use(companyRoutes);
routes.use(planRoutes);
routes.use(ticketNoteRoutes);
routes.use(quickMessageRoutes);
routes.use(helpRoutes);
routes.use(dashboardRoutes);
routes.use(queueOptionRoutes);
routes.use(scheduleRoutes);
routes.use(tagRoutes);
routes.use(contactLabelRoutes);
routes.use(contactListRoutes);
routes.use(contactListItemRoutes);
routes.use(campaignRoutes);
routes.use(campaignSettingRoutes);
routes.use(announcementRoutes);
routes.use(chatRoutes);
routes.use(subscriptionRoutes);
routes.use(invoiceRoutes);
routes.use(ticketTagRoutes);
routes.use(filesRoutes);
routes.use(promptRoutes);
routes.use(queueIntegrationRoutes);
routes.use(forgotsRoutes);

routes.use(flowDefaultRoutes);
routes.use(flowBuilder);
routes.use(flowCampaignRoutes);
routes.use(userRatingRoutes);
routes.use(ratingTemplateRoutes);
routes.use(groupRoutes);
routes.use(appointmentRoutes);
routes.use(crmRoutes);
routes.use(inventoryRoutes);
routes.use(aiAgentRoutes);
routes.use(aiProviderCredentialRoutes);
routes.use(automationOrchestratorRoutes);
routes.use(automationToolsRoutes);
routes.use(automationEvidenceRoutes);
routes.use(automationLiveRolloutRoutes);
routes.use(automationCognitivePlanningRoutes);
routes.use(automationExecutionOrchestratorRoutes);
routes.use(automationActionExecutionRoutes);
routes.use(automationRuntimeIntegrationRoutes);
routes.use(automationExecutionFeedbackRoutes);
routes.use(automationCognitiveMemoryRoutes);
routes.use(automationMcpRoutes);
routes.use(automationLearningRoutes);
routes.use(automationMultiAgentRoutes);
routes.use(automationObservabilityRoutes);
routes.use(automationScalabilityRoutes);
routes.use(automationProductionRoutes);
routes.use(knowledgeBaseRoutes);

export default routes;
