import express from "express";
import isAuth from "../middleware/isAuth";
import { inventoryReceiptLogoUpload } from "../config/inventoryReceiptLogoUpload";
import requireInventorySalesPermission from "../middleware/requireInventorySalesPermission";
import {
  INVENTORY_SALES_CANCEL_SALE,
  INVENTORY_SALES_CREATE_SALE,
  INVENTORY_SALES_MANAGE_CUSTOMERS,
  INVENTORY_SALES_MANAGE_CUSTOMER_CREDIT,
  INVENTORY_SALES_MANAGE_PAYMENTS,
  INVENTORY_SALES_MANAGE_PRODUCTS,
  INVENTORY_SALES_MANAGE_SETTINGS,
  INVENTORY_SALES_MANAGE_STOCK,
  INVENTORY_SALES_RECEIVE_RECEIVABLES,
  INVENTORY_SALES_REVERSE_RECEIVABLE_PAYMENTS,
  INVENTORY_SALES_USE_STORE_CREDIT,
  INVENTORY_SALES_VIEW,
  INVENTORY_SALES_VIEW_CUSTOMERS,
  INVENTORY_SALES_VIEW_CUSTOMER_FINANCIALS,
  INVENTORY_SALES_VIEW_RECEIVABLES,
  INVENTORY_SALES_VIEW_REPORTS,
  InventorySalesGranularKey,
} from "../config/inventorySalesPermissions";
import * as InventoryController from "../controllers/InventoryController";
import * as InventorySaleController from "../controllers/InventorySaleController";
import * as InventorySellerProfileController from "../controllers/InventorySellerProfileController";
import * as InventoryReportController from "../controllers/InventoryReportController";
import * as InventoryDeliveryMethodController from "../controllers/InventoryDeliveryMethodController";
import * as InventoryCustomerController from "../controllers/InventoryCustomerController";
import * as InventoryReceivableController from "../controllers/InventoryReceivableController";

const inventoryRoutes = express.Router();

const viewOrStock: InventorySalesGranularKey[] = [
  INVENTORY_SALES_VIEW,
  INVENTORY_SALES_MANAGE_STOCK,
];

inventoryRoutes.get(
  "/inventory/settings",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_SETTINGS),
  InventoryController.getSettings
);
inventoryRoutes.put(
  "/inventory/settings",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_SETTINGS),
  InventoryController.updateSettings
);
inventoryRoutes.post(
  "/inventory/settings/receipt-logo",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_SETTINGS),
  inventoryReceiptLogoUpload.single("logo"),
  InventoryController.uploadReceiptLogo
);
inventoryRoutes.delete(
  "/inventory/settings/receipt-logo",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_SETTINGS),
  InventoryController.deleteReceiptLogo
);
inventoryRoutes.get(
  "/inventory/receipt-branding",
  isAuth,
  requireInventorySalesPermission(
    INVENTORY_SALES_VIEW,
    INVENTORY_SALES_MANAGE_SETTINGS
  ),
  InventoryController.getReceiptBranding
);

inventoryRoutes.get(
  "/inventory/seller-profiles",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_SETTINGS),
  InventorySellerProfileController.listSellerProfiles
);
inventoryRoutes.post(
  "/inventory/seller-profiles",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_SETTINGS),
  InventorySellerProfileController.createSellerProfile
);
inventoryRoutes.put(
  "/inventory/seller-profiles/:id",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_SETTINGS),
  InventorySellerProfileController.updateSellerProfile
);
inventoryRoutes.delete(
  "/inventory/seller-profiles/:id",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_SETTINGS),
  InventorySellerProfileController.deleteSellerProfile
);

inventoryRoutes.get(
  "/inventory/delivery-methods",
  isAuth,
  requireInventorySalesPermission(
    INVENTORY_SALES_VIEW,
    INVENTORY_SALES_CREATE_SALE,
    INVENTORY_SALES_MANAGE_SETTINGS
  ),
  InventoryDeliveryMethodController.listDeliveryMethods
);
inventoryRoutes.post(
  "/inventory/delivery-methods",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_SETTINGS),
  InventoryDeliveryMethodController.createDeliveryMethod
);
inventoryRoutes.put(
  "/inventory/delivery-methods/:id",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_SETTINGS),
  InventoryDeliveryMethodController.updateDeliveryMethod
);
inventoryRoutes.delete(
  "/inventory/delivery-methods/:id",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_SETTINGS),
  InventoryDeliveryMethodController.deactivateDeliveryMethod
);

inventoryRoutes.get(
  "/inventory/categories",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW),
  InventoryController.listCategories
);
inventoryRoutes.post(
  "/inventory/categories",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PRODUCTS),
  InventoryController.createCategory
);
inventoryRoutes.put(
  "/inventory/categories/:id",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PRODUCTS),
  InventoryController.updateCategory
);
inventoryRoutes.delete(
  "/inventory/categories/:id",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PRODUCTS),
  InventoryController.deleteCategory
);

inventoryRoutes.post(
  "/inventory/stock-movements",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_STOCK),
  InventoryController.createStockMovement
);
inventoryRoutes.get(
  "/inventory/stock-movements",
  isAuth,
  requireInventorySalesPermission(...viewOrStock),
  InventoryController.listStockMovements
);

inventoryRoutes.get(
  "/inventory/reports/summary",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW_REPORTS),
  InventoryReportController.getReportSummary
);
inventoryRoutes.get(
  "/inventory/reports/sellers",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW_REPORTS),
  InventoryReportController.getReportSellers
);
inventoryRoutes.get(
  "/inventory/reports/products",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW_REPORTS),
  InventoryReportController.getReportProducts
);
inventoryRoutes.get(
  "/inventory/reports/customers",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW_REPORTS),
  InventoryReportController.getReportCustomers
);
inventoryRoutes.get(
  "/inventory/reports/receivables",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW_REPORTS),
  InventoryReportController.getReportReceivables
);
inventoryRoutes.get(
  "/inventory/reports/store-credit",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW_REPORTS),
  InventoryReportController.getReportStoreCredit
);

inventoryRoutes.get(
  "/inventory/customers/search",
  isAuth,
  requireInventorySalesPermission(
    INVENTORY_SALES_VIEW,
    INVENTORY_SALES_VIEW_CUSTOMERS,
    INVENTORY_SALES_CREATE_SALE
  ),
  InventorySaleController.searchCustomers
);
inventoryRoutes.get(
  "/inventory/contacts/search",
  isAuth,
  requireInventorySalesPermission(
    INVENTORY_SALES_VIEW,
    INVENTORY_SALES_VIEW_CUSTOMERS,
    INVENTORY_SALES_MANAGE_CUSTOMERS,
    INVENTORY_SALES_CREATE_SALE
  ),
  InventorySaleController.searchContacts
);

inventoryRoutes.get(
  "/inventory/customers",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW_CUSTOMERS),
  InventoryCustomerController.listCustomers
);
inventoryRoutes.post(
  "/inventory/customers",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_CUSTOMERS),
  InventoryCustomerController.createCustomer
);
inventoryRoutes.post(
  "/inventory/customers/from-contact/:contactId",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_CUSTOMERS),
  InventoryCustomerController.createCustomerFromContact
);
inventoryRoutes.get(
  "/inventory/customers/:id",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW_CUSTOMERS),
  InventoryCustomerController.getCustomer
);
inventoryRoutes.put(
  "/inventory/customers/:id",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_CUSTOMERS),
  InventoryCustomerController.updateCustomer
);
inventoryRoutes.post(
  "/inventory/customers/:id/activate",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_CUSTOMERS),
  InventoryCustomerController.activateCustomer
);
inventoryRoutes.post(
  "/inventory/customers/:id/deactivate",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_CUSTOMERS),
  InventoryCustomerController.deactivateCustomer
);
inventoryRoutes.get(
  "/inventory/customers/:id/credit",
  isAuth,
  requireInventorySalesPermission(
    INVENTORY_SALES_VIEW_CUSTOMER_FINANCIALS,
    INVENTORY_SALES_MANAGE_CUSTOMER_CREDIT,
    INVENTORY_SALES_USE_STORE_CREDIT
  ),
  InventoryCustomerController.getCustomerCredit
);
inventoryRoutes.get(
  "/inventory/customers/:id/account",
  isAuth,
  requireInventorySalesPermission(
    INVENTORY_SALES_VIEW_CUSTOMER_FINANCIALS,
    INVENTORY_SALES_MANAGE_CUSTOMER_CREDIT
  ),
  InventoryCustomerController.getCustomerAccount
);
inventoryRoutes.post(
  "/inventory/store-credit/preview",
  isAuth,
  requireInventorySalesPermission(
    INVENTORY_SALES_USE_STORE_CREDIT,
    INVENTORY_SALES_CREATE_SALE
  ),
  InventoryCustomerController.previewStoreCreditSchedule
);

inventoryRoutes.get(
  "/inventory/receivables/summary",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW_RECEIVABLES),
  InventoryReceivableController.getReceivableSummary
);
inventoryRoutes.get(
  "/inventory/receivables",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW_RECEIVABLES),
  InventoryReceivableController.listReceivables
);
inventoryRoutes.get(
  "/inventory/receivables/:id",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW_RECEIVABLES),
  InventoryReceivableController.getReceivable
);
inventoryRoutes.post(
  "/inventory/receivables/:id/payments",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_RECEIVE_RECEIVABLES),
  InventoryReceivableController.createReceivablePayment
);
inventoryRoutes.post(
  "/inventory/receivable-payments/:paymentId/reverse",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_REVERSE_RECEIVABLE_PAYMENTS),
  InventoryReceivableController.reverseReceivablePayment
);
inventoryRoutes.get(
  "/inventory/sales",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW),
  InventorySaleController.listSales
);
inventoryRoutes.post(
  "/inventory/sales",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_CREATE_SALE),
  InventorySaleController.createSale
);
inventoryRoutes.get(
  "/inventory/sales/:id",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW),
  InventorySaleController.showSale
);
inventoryRoutes.put(
  "/inventory/sales/:id",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_CREATE_SALE),
  InventorySaleController.updateSale
);
inventoryRoutes.put(
  "/inventory/sales/:id/delivery",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_CREATE_SALE),
  InventorySaleController.updateSaleDelivery
);
inventoryRoutes.delete(
  "/inventory/sales/:id",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_CANCEL_SALE),
  InventorySaleController.deleteSale
);
inventoryRoutes.post(
  "/inventory/sales/:id/items",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_CREATE_SALE),
  InventorySaleController.addSaleItem
);

inventoryRoutes.put(
  "/inventory/sales/:id/global-discount",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_CREATE_SALE),
  InventorySaleController.updateSaleGlobalDiscount
);
inventoryRoutes.put(
  "/inventory/sales/:id/items/:itemId",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_CREATE_SALE),
  InventorySaleController.updateSaleItem
);
inventoryRoutes.delete(
  "/inventory/sales/:id/items/:itemId",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_CREATE_SALE),
  InventorySaleController.deleteSaleItem
);
inventoryRoutes.post(
  "/inventory/sales/:id/complete",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_CREATE_SALE),
  InventorySaleController.completeSale
);
inventoryRoutes.post(
  "/inventory/sales/:id/cancel",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_CANCEL_SALE),
  InventorySaleController.cancelSale
);
inventoryRoutes.put(
  "/inventory/sales/:id/payment",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PAYMENTS),
  InventorySaleController.updateSalePayment
);
inventoryRoutes.get(
  "/inventory/sales/:id/payments",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PAYMENTS),
  InventorySaleController.listSalePayments
);
inventoryRoutes.post(
  "/inventory/sales/:id/payments",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PAYMENTS),
  InventorySaleController.createSalePayment
);
inventoryRoutes.put(
  "/inventory/sales/:id/payments/:paymentId",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PAYMENTS),
  InventorySaleController.updateSalePaymentLine
);
inventoryRoutes.delete(
  "/inventory/sales/:id/payments/:paymentId",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PAYMENTS),
  InventorySaleController.deleteSalePaymentLine
);
inventoryRoutes.post(
  "/inventory/sales/:id/payments/:paymentId/settle",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PAYMENTS),
  InventorySaleController.settleSalePaymentLine
);

inventoryRoutes.get(
  "/inventory/products/low-stock",
  isAuth,
  requireInventorySalesPermission(...viewOrStock),
  InventoryController.listLowStockProducts
);

inventoryRoutes.get(
  "/inventory/product-attributes",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW),
  InventoryController.listProductAttributes
);
inventoryRoutes.post(
  "/inventory/product-attributes",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PRODUCTS),
  InventoryController.createProductAttribute
);
inventoryRoutes.post(
  "/inventory/product-attributes/:attributeId/options",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PRODUCTS),
  InventoryController.createProductAttributeOption
);

inventoryRoutes.get(
  "/inventory/products",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW),
  InventoryController.listProducts
);
inventoryRoutes.post(
  "/inventory/products",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PRODUCTS),
  InventoryController.createProduct
);
inventoryRoutes.get(
  "/inventory/products/:id/variants",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW),
  InventoryController.listProductVariants
);
inventoryRoutes.post(
  "/inventory/products/:id/variants",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PRODUCTS),
  InventoryController.createProductVariant
);
inventoryRoutes.put(
  "/inventory/products/:id/variants/:variantId",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PRODUCTS),
  InventoryController.updateProductVariant
);
inventoryRoutes.get(
  "/inventory/products/:id/stock-movements",
  isAuth,
  requireInventorySalesPermission(...viewOrStock),
  InventoryController.listProductStockMovements
);
inventoryRoutes.get(
  "/inventory/products/:id",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_VIEW),
  InventoryController.showProduct
);
inventoryRoutes.put(
  "/inventory/products/:id",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PRODUCTS),
  InventoryController.updateProduct
);
inventoryRoutes.delete(
  "/inventory/products/:id",
  isAuth,
  requireInventorySalesPermission(INVENTORY_SALES_MANAGE_PRODUCTS),
  InventoryController.deleteProduct
);

export default inventoryRoutes;
