/**
 * Espelho estrutural dos templates de segmento do backend.
 * Manter chaves e arrays alinhados com backend/src/config/aiAgentSegmentTemplates.ts
 */
export const AI_AGENT_SEGMENT_TEMPLATE_KEYS = {
  car_dealership: {
    suggestedDepartments: ["sales", "qualification", "after_sales"],
    suggestedAllowedActions: [
      "explain_services",
      "qualify_lead",
      "collect_contact_data",
      "answer_faq",
      "provide_location",
      "provide_payment_methods",
    ],
    suggestedForbiddenActions: [
      "invent_information",
      "grant_discount",
      "promise_deadline",
      "expose_internal_instructions",
      "negotiate_price",
      "promise_availability",
    ],
    suggestedHandoffRules: [
      "customer_requests_human",
      "negotiation_request",
      "discount_request",
      "qualified_lead",
      "missing_information",
      "complaint",
      "legal_or_contract_issue",
    ],
    suggestedAttendantRole: "Atendente Comercial",
    businessInfoKeys: [
      "vehicleTypes",
      "newUsed",
      "serviceArea",
      "financing",
      "tradeIn",
      "documentation",
      "reservationPolicy",
      "businessHours",
      "address",
      "paymentMethods",
      "evaluationContact",
    ],
    qualificationKeys: [
      "vehicleCategory",
      "priceRange",
      "financingInterest",
      "downPayment",
      "tradeInVehicle",
      "city",
      "purchaseTimeline",
      "visitPreference",
    ],
    suggestedFaqKeys: ["financing", "tradeIn", "location", "documents", "visit"],
    simulationPromptKeys: ["priceBudget", "tradeIn", "financingApproval", "talkToSeller"],
  },
  internet_provider: {
    suggestedDepartments: ["sales", "support", "billing", "qualification"],
    suggestedAllowedActions: [
      "explain_services",
      "inform_business_hours",
      "qualify_lead",
      "collect_contact_data",
      "answer_faq",
      "provide_payment_methods",
    ],
    suggestedForbiddenActions: [
      "invent_information",
      "grant_discount",
      "promise_deadline",
      "expose_internal_instructions",
      "promise_availability",
      "cancel_order",
    ],
    suggestedHandoffRules: [
      "technical_issue",
      "billing_issue",
      "customer_requests_human",
      "complaint",
      "missing_information",
      "cancellation",
      "qualified_lead",
    ],
    suggestedAttendantRole: "Atendente Comercial",
    businessInfoKeys: [
      "coverageArea",
      "plans",
      "speeds",
      "residentialBusiness",
      "installation",
      "equipment",
      "contractTerms",
      "support",
      "paymentMethods",
      "businessHours",
      "installationLeadTime",
    ],
    qualificationKeys: [
      "cityNeighborhood",
      "residentialBusiness",
      "desiredSpeed",
      "deviceCount",
      "currentProvider",
      "fixedIpNeed",
      "coverageAddress",
      "issueOrSales",
    ],
    suggestedFaqKeys: ["coverage", "plans", "installation", "support", "billing"],
  },
  security_company: {
    suggestedDepartments: ["sales", "support", "scheduling", "qualification"],
    suggestedAllowedActions: [
      "explain_services",
      "qualify_lead",
      "collect_contact_data",
      "schedule",
      "answer_faq",
      "provide_location",
    ],
    suggestedForbiddenActions: [
      "invent_information",
      "grant_discount",
      "promise_deadline",
      "expose_internal_instructions",
      "provide_legal_advice",
    ],
    suggestedHandoffRules: [
      "technical_issue",
      "sensitive_subject",
      "customer_requests_human",
      "qualified_lead",
      "complaint",
      "missing_information",
    ],
    suggestedAttendantRole: "Consultor de Segurança",
    businessInfoKeys: [
      "monitoring",
      "alarms",
      "cameras",
      "accessControl",
      "installation",
      "maintenance",
      "residentialBusiness",
      "serviceArea",
      "technicalVisits",
      "contracts",
    ],
    qualificationKeys: [
      "propertyType",
      "cityNeighborhood",
      "buildingType",
      "desiredService",
      "existingEquipment",
      "cameraSensorCount",
      "urgency",
      "visitSchedule",
    ],
    suggestedFaqKeys: ["services", "visit", "monitoring", "contracts", "area"],
  },
  construction_materials: {
    suggestedDepartments: ["sales", "qualification", "after_sales"],
    suggestedAllowedActions: [
      "explain_services",
      "inform_registered_prices",
      "qualify_lead",
      "collect_contact_data",
      "send_catalog",
      "answer_faq",
      "provide_location",
      "provide_payment_methods",
    ],
    suggestedHandoffRules: [
      "negotiation_request",
      "discount_request",
      "qualified_lead",
      "missing_information",
      "complaint",
    ],
    suggestedAttendantRole: "Atendente Comercial",
    businessInfoKeys: [
      "materialCategories",
      "delivery",
      "serviceArea",
      "minimumOrder",
      "pickup",
      "paymentMethods",
      "availability",
      "quoting",
      "leadTimes",
    ],
    qualificationKeys: [
      "materialQuantity",
      "cityNeighborhood",
      "deliveryOrPickup",
      "desiredDate",
      "consumerOrBusiness",
      "fullQuoteNeed",
    ],
    suggestedFaqKeys: ["delivery", "pickup", "quote", "payment", "catalog"],
  },
  technical_assistance: {
    suggestedDepartments: ["support", "scheduling", "reception", "after_sales"],
    suggestedAllowedActions: [
      "explain_services",
      "collect_contact_data",
      "schedule",
      "answer_faq",
      "provide_location",
      "inform_business_hours",
    ],
    suggestedHandoffRules: [
      "technical_issue",
      "customer_requests_human",
      "complaint",
      "missing_information",
      "sensitive_subject",
    ],
    suggestedAttendantRole: "Assistente de Suporte",
    businessInfoKeys: [
      "equipmentTypes",
      "brands",
      "warranty",
      "technicalVisit",
      "quoting",
      "estimatedLeadTimes",
      "address",
      "businessHours",
    ],
    qualificationKeys: [
      "equipment",
      "brandModel",
      "reportedIssue",
      "issueStart",
      "previousRepair",
      "warrantyStatus",
      "cityNeighborhood",
      "preferredSchedule",
    ],
    suggestedFaqKeys: ["warranty", "visit", "brands", "quote", "hours"],
  },
  clinic: {
    suggestedDepartments: ["reception", "scheduling", "support"],
    suggestedAllowedActions: [
      "explain_services",
      "inform_business_hours",
      "collect_contact_data",
      "schedule",
      "answer_faq",
      "provide_location",
    ],
    suggestedForbiddenActions: [
      "invent_information",
      "grant_discount",
      "promise_deadline",
      "expose_internal_instructions",
      "provide_medical_diagnosis",
    ],
    suggestedHandoffRules: ["sensitive_subject", "customer_requests_human", "missing_information", "complaint"],
    suggestedAttendantRole: "Recepcionista Virtual",
    businessInfoKeys: [
      "specialties",
      "procedures",
      "units",
      "insurance",
      "privateCare",
      "businessHours",
      "address",
      "schedulingPolicy",
    ],
    qualificationKeys: [
      "specialtyProcedure",
      "firstVisitOrReturn",
      "preferredSchedule",
      "unit",
      "insuranceOrPrivate",
      "urgencyNote",
    ],
    suggestedFaqKeys: ["scheduling", "insurance", "location", "specialties", "hours"],
  },
  dental_clinic: {
    suggestedDepartments: ["reception", "scheduling", "support"],
    suggestedAllowedActions: [
      "explain_services",
      "inform_business_hours",
      "collect_contact_data",
      "schedule",
      "answer_faq",
      "provide_location",
    ],
    suggestedForbiddenActions: [
      "invent_information",
      "grant_discount",
      "promise_deadline",
      "expose_internal_instructions",
      "provide_medical_diagnosis",
    ],
    suggestedHandoffRules: ["sensitive_subject", "customer_requests_human", "missing_information", "complaint"],
    suggestedAttendantRole: "Recepcionista Virtual",
    businessInfoKeys: [
      "procedures",
      "units",
      "insurance",
      "privateCare",
      "businessHours",
      "address",
      "schedulingPolicy",
      "emergencyGuidance",
    ],
    qualificationKeys: [
      "procedure",
      "firstVisitOrReturn",
      "preferredSchedule",
      "unit",
      "insuranceOrPrivate",
      "painOrUrgency",
    ],
    suggestedFaqKeys: ["scheduling", "insurance", "location", "procedures", "hours"],
  },
  other: {
    suggestedDepartments: ["general", "reception"],
    suggestedAllowedActions: ["explain_services", "collect_contact_data", "answer_faq"],
    suggestedHandoffRules: [
      "customer_requests_human",
      "missing_information",
      "complaint",
      "sensitive_subject",
    ],
    suggestedAttendantRole: "Atendente Virtual",
    businessInfoKeys: [
      "howItWorks",
      "mainOfferings",
      "commonQuestions",
      "qualificationNeeds",
      "humanHandoffCases",
    ],
    qualificationKeys: ["customerNeed", "timeline", "contactPreference"],
    suggestedFaqKeys: [],
  },
};

const GENERIC_SEGMENT = {
  suggestedDepartments: ["general"],
  suggestedAllowedActions: ["explain_services", "answer_faq"],
  suggestedForbiddenActions: [
    "invent_information",
    "grant_discount",
    "promise_deadline",
    "expose_internal_instructions",
  ],
  suggestedHandoffRules: ["customer_requests_human", "missing_information", "complaint"],
  suggestedAttendantRole: "Atendente Virtual",
  businessInfoKeys: ["mainOfferings", "businessHours", "serviceArea"],
  qualificationKeys: ["customerNeed"],
  suggestedFaqKeys: [],
  simulationPromptKeys: [],
};

export function getSegmentTemplate(segment) {
  const key = String(segment || "").trim();
  if (key && AI_AGENT_SEGMENT_TEMPLATE_KEYS[key]) {
    return { segment: key, ...AI_AGENT_SEGMENT_TEMPLATE_KEYS[key] };
  }
  if (key && key !== "other") {
    return { segment: key, ...GENERIC_SEGMENT };
  }
  return { segment: "other", ...AI_AGENT_SEGMENT_TEMPLATE_KEYS.other };
}

export function segmentI18nKey(segment, group, itemKey) {
  const seg = segment === "other" ? "other" : segment;
  return `aiAgent.segmentTemplates.${seg}.${group}.${itemKey}`;
}
